---
#comment
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: onboarding-deployment
  name: onboarding-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      name: onboarding-deployment
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: onboarding-deployment
    spec:
      containers:
        - name: onboarding-docker-deploy
          image: "p00342-onboarding.docker.ing.net/onboardingdemo:20318"
          imagePullPolicy: Always
          ports:
            - containerPort: nap
              name: http
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 100m
              memory: 100Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      imagePullSecrets:
        - name: onboarding-pullsecret
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30