---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    name: onboarding-route
  name: onboarding-route
spec:
  port:
    targetPort: 8080
  tls:
    termination: edge
  to:
    kind: Service
    name: onboarding-service
    weight: 100
  wildcardPolicy: None