---
apiVersion: v1
kind: Service
metadata:
  labels:
    name:  onboarding-service
  name:  onboarding-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    name: onboarding-deployment
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}