---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: {{ .Values.service.name }}
  name: {{ .Values.service.name }}
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    name: {{ .Values.deployment.name }}
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}